"""empty message

Revision ID: 61199bb17dcb
Revises: f47b18f4ade9
Create Date: 2021-03-14 20:00:18.863539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61199bb17dcb'
down_revision = 'f47b18f4ade9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
